config/routes.rb
Rails.application.routes.draw do
  get '/' => 'products#index'
  resources :products, only: :index do
    collection do
      post :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  # メルカリ
  def self.mercari(keyword, number)
    agent = Mechanize.new

    # 100ページあるため取得ページ数を任意で指定
    (1..number.to_i).each do |i|
      page = agent.get("https://www.mercari.com/jp/search/?page=#{i}&keyword=#{keyword}")
      elements = page.search('section.items-box')

      # 1ページ単位での商品情報取得
      elements.each do |element|
        name = element.search('h3.items-box-name').text
        image = element.at('img').get_attribute('data-src')
        url = element.at('a').get_attribute('href')
        price = element.at('div.items-box-price').text
        sold = element.at('div.item-sold-out-badge')
        Product.create(
          name: name,
          image_url: image,
          product_url: url,
          price: price,
          is_sold: sold.present? ? false : true,
          service: 0
        )
      end
    end
  end

  # ヤフオク
  def self.yahoo_auction(keyword, number)
    agent = Mechanize.new

    # 取得ページ数を任意で指定
    (1..number.to_i).each do |i|
      page = agent.get("https://auctions.yahoo.co.jp/search/search?p=#{keyword}&b=#{((i - 1) * 50) + 1}&n=50")
      elements = page.search('li.Product')

      # 1ページ単位での商品情報取得
      elements.each do |element|
        name = element.search('a.Product__titleLink').text
        image = element.at('img.Product__imageData').get_attribute('src')
        url = element.at('a.Product__imageLink').get_attribute('href')
        price = element.at('span.Product__priceValue').text
        summary_price = element.search('span.Product__priceValue')
        remaining_time = element.at('span.Product__time').text
        bid_number = element.at('span.Product__bid').text
        shipping = element.at('span.Product__icon--freeShipping')
        sold = element.at('span.Product__time')
        attention = element.at('span.Product__icon--attention')

        # 1ページ目に「注目度top3の商品」が3点表示されるため省く
        if attention.blank?
          Product.create(
            name: name,                                                             # 商品名
            image_url: image,                                                       # 画像URL
            product_url: url,                                                       # 商品URL
            price: price,                                                           # 価格
            summary_price: summary_price.length == 1 ? nil : summary_price[1].text, # 即決価格
            remaining_time: remaining_time,                                         # 残り時間
            bid_number: bid_number,                                                 # 入札数
            shipping: shipping.present? ? true : false,                             # 送料無料
            is_sold: 1,                                                             # 売り切れ
            service: 1                                                              # メルカリかヤフオク）
          )
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :destroy_all, only: :search

  def index
    @products = Product.page(params[:page]).per(100)
    # @products = Product.page(params[:page]).per(Product::PER)
  end

  def search
    if params[:service].to_i == 1
      Product.mercari(params[:name], params[:number])
      redirect_to products_path(keyword: params[:name], number: params[:number], service: params[:service])
    elsif params[:service].to_i == 2 then
      Product.yahoo_auction(params[:name], params[:number])
      redirect_to products_path(keyword: params[:name], number: params[:number], service: params[:service])
    end
  end

  private

  def destroy_all
    products = Product.all
    products.destroy_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ScrapingStudy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/products/_tbody.html.slim
tbody
  - @products.each do |product|

    / メルカリ
    - if product.service == 0
      tr
        td.text-center.align-middle = image_tag product.image_url, class: 'image'
        td.text-center.align-middle = product.name.truncate(45)
        td.text-center.align-middle = product.price
        td.text-center.align-middle = product.is_sold ? '販売中' : '売り切れ'

    / ヤフオク
    - elsif product.service == 1 then
      tr
        td.text-center.align-middle = image_tag product.image_url, class: 'image'
        td.text-center.align-middle = product.name.truncate(45)
        td.text-center.align-middle 
          = product.price
          = "（送料別）" if product.shipping?
          br
          p style="color: red;" = "即決価格:#{product.summary_price}" if product.summary_price.present?
        td.text-center.align-middle
          = "残り#{product.remaining_time}"
          br
          = "入札数:#{product.bid_number}"

app/views/products/_thead.html.slim
thead.thead-light
  tr
    th.text-center 画像
    th.text-center 商品名
    th.text-center 値段
    th.text-center 販売状況

app/views/products/index.html.slim
/ 一覧ページ
.container.mt-5

  / 検索フォーム
  .float-left
    = form_tag search_products_path do
      .form-inline.mb-3
        = label_tag :検索ワード
        = text_field_tag :name, params[:keyword], class: 'form-control mx-3'
        = label_tag :取得ページ数
        = number_field_tag :number, params[:number], min: 1, class: 'form-control mx-3'
      .form-inline.mb-3
        = label_tag :検索対象サイト
        = radio_button_tag :service, '1', params[:service].blank? || params[:service].to_i == 1, class: 'form-control ml-3'
        = label_tag :service_1, 'メルカリ'
        = radio_button_tag :service, '2', params[:service].to_i == 2, class: 'form-control ml-3'
        = label_tag :service_2, 'ヤフオク'
        = submit_tag '検索', class: 'btn btn-primary ml-3'

  / ページネーション
  .float-right
    = paginate @products

  / テーブル
  table.table.table-bordered.table-striped.table-hover.table-sm.mb-5
    == render 'thead'
    == render 'tbody'

  / ページネーション
  .float-right
    = paginate @products